<a href="https://colab.research.google.com/github/Duban1922/Dub_1922/blob/main/estructuradata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. **Linear Algebra**


## 1.1 Library

## 1.2 Creation

In [6]:
# Libraries
import numpy as np


In [9]:
# Column vector
x = np.array([[1],[2],[3]])
print(x)
print(x.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [12]:
# Row vector
np.array([[1,2,3]])
y = np.array([[4,5,6]])
print(y)
print(y.shape)

[[4 5 6]]
(1, 3)


In [15]:
A =   np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


1.3. Sliceing


In [20]:
# Extract 1 element

## Give the coordinates

print("the firts element of x", x[0])
print("the firts element of x", y[0])
print("the firts element of x", y[0,0]) ## Traer solo un elemento
print("the firts element of A", A[2,1])

the firts element of x [1]
the firts element of x [4 5 6]
the firts element of x 4
the firts element of A 8


In [23]:
# eXtract more than 1
print("the first two rows of x", x[0:2]) ## traer mas de 2 elementos
print("the first two colums of y", y[0,0:2])
print("the first two colums and rows of A", A[0:2,0:2])

the first two rows of x [[1]
 [2]]
the first two colums of y [4 5]
the first two colums and rows of A [[1 2]
 [4 5]]


In [24]:
# Find Value
## find the position of the number 5 in A

np.where(A == 5)

(array([1]), array([1]))

## 1.4. Methods


In [30]:
# Zeros
## Create vectors of matrices of only 0

z1 = np.zeros(5)
print(z1)

z2 = np.zeros((5,1))
print(z2)

z3 = np.zeros((5,5))
print(z3)

[0. 0. 0. 0. 0.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
# Ones
## Create vectors of matrices of only 1

h1 = np.ones(5)
print(h1)

h2 = np.ones((5,1))
print(h2)

h3 = np.ones((5,5))
print(h3)

[1. 1. 1. 1. 1.]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 1.5. Random Numbers



### Uniform distribution  [0,1]



In [42]:
np.random.rand()

0.9127504520239486

In [43]:
# Example - Coin toss

if np.random.rand() < 0.5:
  print("Heads")
else:
  print("Tails")

Tails
